#!/bin/bash

nrpecfg="/etc/nagios/nrpe.cfg"
tmpfile="/tmp/nrpe_run_all.tmp"

incfiles=$(cat $nrpecfg | grep "^include" | cut -d= -f2)
$(cat $nrpecfg | grep "^command\[" | cut -d= -f2 >> $tmpfile)
cn=$(cat $nrpecfg | grep "^command\[" | cut -d[ -f2 | cut -d] -f1)

function getcoms() {
	for file in ${incfiles[@]}
	do
		if [ -d "$file" ]; then
			incfiles="$file*"
			getcoms
		else
			$(cat $file | grep "^command\[" | cut -d= -f2 >> $tmpfile)
			cn="$cn $(cat $file | grep "^command\[" | cut -d[ -f2 | cut -d] -f1)"
		fi
	done
}

getcoms
i=0
while [ "$i" -lt "$(wc -l $tmpfile | cut -d' ' -f1)" ];
do
	i=$[$i + 1];
	printf "%-25s: " $(echo $cn | cut -d' ' -f$i)
	$(echo $(cat $tmpfile | head -$i | tail -1))
done

$(rm $tmpfile) 