#!/bin/bash

nrpecfg="/etc/nagios/nrpe.cfg"
tmpfile=$(mktemp)

incfiles=$(cat $nrpecfg | grep "^include" | cut -d= -f2)
$(cat $nrpecfg | grep "^command\[" | cut -d= -f2 >> $tmpfile)
cn=$(cat $nrpecfg | grep "^command\[" | cut -d[ -f2 | cut -d] -f1)

function getcoms()
{
	for file in ${incfiles[@]}
	do
		if [ -d "$file" ]; then
			if [ $(ls $file | grep -E '\.cfg$' | wc -l) -gt 0 ]; then
				incfiles="$file*.cfg"
				getcoms
			fi
		else
			$(cat $file | grep "^command\[" | cut -d= -f2 >> $tmpfile)
			cn="$cn $(cat $file | grep "^command\[" | cut -d[ -f2 | cut -d] -f1)"
		fi
	done
}

getcoms
i=0
while [ "$i" -lt "$(wc -l  < $tmpfile)" ];
do
	i=$[$i + 1];
	printf "%-25s: " $(echo $cn | cut -d' ' -f$i)
	{ mispipe "$(echo $(cat $tmpfile | head -$i | tail -1))" "cut -d'|' -f1"; echo "EXIT:$?"; } | paste -s
done

rm $tmpfile 
